### PR TITLE
Fix completion minimum pattern length

### PR DESCRIPTION
**Pull request by tony**
See also: https://git.io/vzWX4
Related: #463

### CODE REVIEW

**Comment by xaizek** [comment]
Thanks, although I doubt it's related to #463, no mentions of neovim there and this code is run only there.

**Comment by expipiplus1** [comment]
With this change I'm seeing the popup menu constantly which isn't particularly pleasant. Is this something other's are experiencing or should I start chopping up my config to discover what's up?

**Comment by tony** [comment]
@expipiplus1 We can revert it if it's causing an issue.

No offense taken here, autocompletion in vim is lost on me. Its so convoluted there is little way to determine what is coming from what.

**Comment by expipiplus1** [comment]
@tony The latest bit of chatter in https://github.com/Rip-Rip/clang_complete/pull/464 is about making this behave a little better.

I couldn't agree more about completion in vim being a mess, it's such a shame.

Perhaps @Shougo could shed some light here.

**Pull request merged**
