### PR TITLE
Added CXCursor_TypeAliasTemplateDecl to the list

### LINKED ISSUE #488: Error detected while processing function ClangComplete
I'm getting following error:

	libclang code completion
	========================
	Command: clang -Wall -Wextra -Werror -std=c++11 -I/home/paladin/utils/3rd_party/gtest/googlemock/include -I/home/paladin/utils/3rd_party/gtest/googletest/include -I/ho
	me/paladin/utils/include -I/usr/include -x c++ -I/../lib/clang/3.9.0/include/ -fsyntax-only  -Xclang -code-completion-at=/home/paladin/utils/tests/id.cpp:46:5 /home/pa
	ladin/utils/tests/id.cpp
	cwd: None
	File: /home/paladin/utils/tests/id.cpp
	Line: 46, Column: 5

	^I^I::

	Error detected while processing function ClangComplete:
	line   22:
	Traceback (most recent call last):
	Error detected while processing function ClangComplete:
	line   22:
	  File "<string>", line 1, in <module>
	Error detected while processing function ClangComplete:
	line   22:
	  File "/home/paladin/dotfiles/.vim/vundle/clang_complete/plugin/libclang.py", line 512, in getCurrentCompletions
	Error detected while processing function ClangComplete:
	line   22:
		result = map(formatResult, results)
	Error detected while processing function ClangComplete:
	line   22:
	  File "/home/paladin/dotfiles/.vim/vundle/clang_complete/plugin/libclang.py", line 421, in formatResult
	Error detected while processing function ClangComplete:
	line   22:
		completion['kind'] = kinds[result.cursorKind]
	Error detected while processing function ClangComplete:
	line   22:
	KeyError: 601
	Error detected while processing function ClangComplete:
	line   23:
	Traceback (most recent call last):
	Error detected while processing function ClangComplete:
	line   23:
	  File "<string>", line 1, in <module>
	Error detected while processing function ClangComplete:
	line   23:
	NameError: name 'completions' is not defined
	Error detected while processing function ClangComplete:
	line   24:
	Traceback (most recent call last):
	Error detected while processing function ClangComplete:
	line   24:
	  File "<string>", line 1, in <module>
	Error detected while processing function ClangComplete:
	line   24:
	NameError: name 'timer' is not defined
	Error detected while processing function ClangComplete:
	line   45:
	Traceback (most recent call last):
	Error detected while processing function ClangComplete:
	line   45:
	  File "<string>", line 1, in <module>
	Error detected while processing function ClangComplete:
	line   45:
	NameError: name 'timer' is not defined
	clang_complete: completion time 4.967418
	Error detected while processing function ClangComplete:
	line   50:
	E121: Undefined variable: l:res
	Error detected while processing function ClangComplete:
	line   50:
	E15: Invalid expression: l:res

### PR DESCRIPTION
**Pull request by graywolf**
Added CXCursor_TypeAliasTemplateDecl (601) to the list.

Fixes #488

### CODE REVIEW

**Comment by xaizek** [comment]
Thanks!

**Comment by graywolf** [comment]
When I have a bit of free time I'll into how to do this by script

**Review by silje7 — COMMENTED** [review]
Ja

**Review by silje7 — COMMENTED** [review]
K

**Pull request merged**
