### PR TITLE
Python 3 (and 2) compatibility.

### LINKED ISSUE #430: [FEATURE REQUEST] Add support for python3
Since python3 is becoming default python in more and more distros,
what about support vim which enables +python3 ?

Thanks

### PR DESCRIPTION
**Pull request by duganchen**
This is the Python 3 compatibility (and Python 2 backward-compatibility) fix in [myint's fork](https://github.com/myint/clang-complete), as a single merge-ready changeset. Merging it will resolve #430.

This pull request is based on the master branch and contains only what's needed for Python 3 compatibility. I've tested it in both Python 2 and Python 3.

### CODE REVIEW

**Comment by duganchen** [comment]
Hmm... I didn't notice that you already have a "support-python3"  branch. :/

I'll leave this open, and you can can close it as you see fit

**Comment by duganchen** [comment]
Naah. Sorry about this.

**Comment by xaizek** [comment]
Thanks for this anyway, I saw a couple more places that needed an update. Does `support-python3` branch work for you? I'm collecting feedback to merge it into master as I only did several simple tests myself.

**Comment by duganchen** [comment]
The support-python3 branch works great for me.

**Pull request closed without merging**
